//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaubaladu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public string Cathegory { get; set; }
        public string Origin { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Owner { get; set; }
    }
}
